# Generated by Django 2.2.9 on 2020-03-07 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('subject', '0001_initial'),
        ('institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconcept',
            name='concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Concept'),
        ),
        migrations.AddField(
            model_name='userconcept',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studymaterialfile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Language'),
        ),
        migrations.AddField(
            model_name='studymaterialfile',
            name='study_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.StudyMaterial'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Content'),
        ),
        migrations.AddField(
            model_name='questiontocmapping',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Question'),
        ),
        migrations.AddField(
            model_name='questiontocmapping',
            name='toc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.TOC'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Language'),
        ),
        migrations.AddField(
            model_name='questionstatement',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Question'),
        ),
        migrations.AddField(
            model_name='questionoptionsstatement',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Language'),
        ),
        migrations.AddField(
            model_name='questionoptionsstatement',
            name='question_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.QuestionOptions'),
        ),
        migrations.AddField(
            model_name='questionoptionsexplanation',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Language'),
        ),
        migrations.AddField(
            model_name='questionoptionsexplanation',
            name='question_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.QuestionOptions'),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Question'),
        ),
        migrations.AddField(
            model_name='notesaccesslog',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AddField(
            model_name='notesaccesslog',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.StudyMaterialFile'),
        ),
        migrations.AddField(
            model_name='notesaccesslog',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Language'),
        ),
        migrations.AddField(
            model_name='notesaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturetocmapping',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Lecture'),
        ),
        migrations.AddField(
            model_name='lecturetocmapping',
            name='toc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.TOC'),
        ),
        migrations.AddField(
            model_name='lecturetoccontent',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Batch'),
        ),
        migrations.AddField(
            model_name='lecturetoccontent',
            name='content_toc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ContentTOCMapping'),
        ),
        migrations.AddField(
            model_name='lecturetoccontent',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Batch'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='classs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Classs'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Phase'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Program'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Sessions'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Assessment'),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Batch'),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='classs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Classs'),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Phase'),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Program'),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.Sessions'),
        ),
        migrations.AddField(
            model_name='dppplanner',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='contenttocmapping',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsectionquestion',
            name='assessment_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.AssessmentSection'),
        ),
        migrations.AddField(
            model_name='assessmentsectionquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Question'),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Language'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Content'),
        ),
        migrations.AddField(
            model_name='assesmentattemptquestion',
            name='assessment_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.AssessmentAttempt'),
        ),
        migrations.AddField(
            model_name='assesmentattemptquestion',
            name='options',
            field=models.ManyToManyField(blank=True, to='content.QuestionOptions'),
        ),
        migrations.AddField(
            model_name='assesmentattemptquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.AssessmentSectionQuestion'),
        ),
    ]
