# Generated by Django 2.2.9 on 2020-03-07 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentclasspath',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institute.Classs'),
        ),
        migrations.AddField(
            model_name='studentclasspath',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionprogram', to='institute.Program'),
        ),
        migrations.AddField(
            model_name='sessionprogram',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='institute.Sessions'),
        ),
        migrations.AddField(
            model_name='programclasssubject',
            name='program_has_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_class', to='institute.ProgramClass'),
        ),
        migrations.AddField(
            model_name='programclasssubject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='programclass',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institute.Classs'),
        ),
        migrations.AddField(
            model_name='programclass',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='institute.Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_name', to='institute.Target'),
        ),
        migrations.AddField(
            model_name='phase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phase',
            name='session_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='institute.SessionProgram'),
        ),
        migrations.AddField(
            model_name='cscdetails',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.CscDetails'),
        ),
        migrations.AddField(
            model_name='classs',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='institute.CscDetails'),
        ),
        migrations.AddField(
            model_name='center',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='institute.CscDetails'),
        ),
        migrations.AddField(
            model_name='center',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='institute.CscDetails'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='institute.Phase'),
        ),
    ]
